const TWITTER_STREAM_INVALID_FORMAT = 'Invalid text format';
const TWITTER_STREAM_UNKNOWN_COORDS = 'Could not get location coords';
const TWITTER_STREAM_WAKE_DISPATCH_ID = '370282363';

module.exports = {
    DEBUG_ERROR_TEXT: [
        TWITTER_STREAM_INVALID_FORMAT,
        TWITTER_STREAM_UNKNOWN_COORDS
    ],
    SERVER: {
        HOST: '0.0.0.0',
        PORT: 3000
    },
    TWITTER_STREAM: {
        INVALID_FORMAT: TWITTER_STREAM_INVALID_FORMAT,
        UNKNOWN_COORDS: TWITTER_STREAM_UNKNOWN_COORDS,
        WAKE_DISPATCH_ID: TWITTER_STREAM_WAKE_DISPATCH_ID
    }
};